In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 0.75951044, -0.34234689,  0.12316892,  0.81646751,  0.95432421,
        0.43852001, -2.25000312,  0.13187558,  0.20646211,  0.74530603])

In [7]:
B = np.random.randn(10)
B

array([ -1.74577552e+00,   1.01704011e+00,  -9.19856778e-01,
         5.94249117e-01,  -6.37974822e-01,  -2.88803956e-01,
        -3.98649226e-04,   1.78996696e-01,   9.80830605e-01,
         1.79498774e-01])

In [8]:
# Binary Functions
np.add(A,B)

array([-0.98626508,  0.67469322, -0.79668786,  1.41071662,  0.31634939,
        0.14971605, -2.25040177,  0.31087228,  1.18729272,  0.9248048 ])

In [9]:
np.maximum(A,B)

array([  7.59510444e-01,   1.01704011e+00,   1.23168921e-01,
         8.16467507e-01,   9.54324210e-01,   4.38520006e-01,
        -3.98649226e-04,   1.78996696e-01,   9.80830605e-01,
         7.45306030e-01])